DROP TABLE IF EXISTS ODONTOLOGOS;

CREATE TABLE ODONTOLOGOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MATRICULA VARCHAR(100) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL
);

INSERT INTO ODONTOLOGOS(MATRICULA, NOMBRE, APELLIDO)
VALUES ('345991232', 'Andres', 'Vallejo');
INSERT INTO ODONTOLOGOS(MATRICULA, NOMBRE, APELLIDO)
VALUES ('99213434', 'Cristian', 'Gonzales');
INSERT INTO ODONTOLOGOS(MATRICULA, NOMBRE, APELLIDO)
VALUES ('88277123', 'Lorena', 'Medina');
INSERT INTO ODONTOLOGOS(MATRICULA, NOMBRE, APELLIDO)
VALUES ('345991232', 'German', 'Villarreal');
INSERT INTO ODONTOLOGOS(MATRICULA, NOMBRE, APELLIDO)
VALUES ('345991232', 'Ximena', 'Suarez');